import React,{useState} from 'react';
import {defaults,evaluate,rankMaps,validateBundle} from './core/model.mjs';
import {syntheticBundle} from './data/synthetic.mjs';
import StateView from './components/StateView.jsx';
import MolecularView from './components/MolecularView.jsx';
import ExperimentView from './components/ExperimentView.jsx';
import Provenance from './components/Provenance.jsx';
import BrainView from './components/BrainView.jsx';
export default function App(){
 const [tab,setTab]=useState(3),[params,setParams]=useState({...defaults}),[bundle,setBundle]=useState(syntheticBundle),[profileId,setProfileId]=useState('synthetic'),[notice,setNotice]=useState('');
 const profile=bundle.profiles.find(p=>p.id===profileId)||bundle.profiles[0];const result=evaluate(params);
 const update=(key,value)=>setParams(p=>({...p,[key]:value}));
 const reset=()=>setParams({...defaults});
 function go(value){setTab(value);setNotice('');}
 async function onImport(event){const file=event.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error('Use an aggregate JSON smaller than 1 MB.');const data=validateBundle(JSON.parse(await file.text()));setBundle(data);setProfileId(data.profiles[0].id);setNotice(`Loaded ${data.regions.length} regions, ${data.profiles.length} profiles and ${data.maps.length} reference maps into local memory.`);}catch(e){setNotice(`Import rejected: ${e.message}`);}event.target.value='';}
 function onSynthetic(){setBundle(syntheticBundle);setProfileId('synthetic');setNotice('Restored the portable synthetic example.');}
 function exportEvidence(){const data={project:'DopaTeam',version:'0.4.0',exportedAt:new Date().toISOString(),claim:'Function is not identifiable from the specified fixed structural and reference-map observations within this illustrative observation model.',dataKind:bundle.kind,source:bundle.source,profile:{id:profile.id,label:profile.label},parameters:params,result,associations:rankMaps(profile.values,bundle.maps).map(m=>({id:m.id,name:m.name,rho:m.rho})),inference:'Descriptive associations only. No spatial null inference. No clinical or cellular validation.',limitations:['S is latent, not MRI volume or neuron count.','F=S*C and thresholds are toy assumptions.','An independent scalar functional measurement separates the constructed pair only.','SST attribution needs cell identity plus functional evidence.','No real transition clock is identified.'],priorResearch:'João Valério Rocha and collaborators, MINNT. Predates the hackathon.',newContribution:'Original conditional simulation, audit interface and measurement comparison.',rawImportedArraysIncluded:false};const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.href=url;a.download='dopateam_evidence.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('Evidence exported locally. No data was sent.');}
 return <><header><div className="wordmark">DopaTeam</div><span className="workspace-label">Research workspace</span><button className="outline" onClick={tab===3?()=>go(0):exportEvidence}>{tab===3?'Open research workflow':'Export evidence'}</button></header><main className={tab===3?'brain-mode':''}>{tab!==3&&<div className="hero"><h1>Same scan. Different cell states.</h1><p>Test what MRI and neurotransmitter maps can tell us about neuronal function.</p></div>}<nav className="workflow" aria-label="Research workflow"><button className={tab===3?'active':''} onClick={()=>go(3)} aria-current={tab===3?'step':undefined}>3D <span>Brain atlas</span></button>{['Molecular context','Competing states','Next experiment'].map((name,i)=><button key={name} className={tab===i?'active':''} onClick={()=>go(i)} aria-current={tab===i?'step':undefined}>{i+1} <span>{name}</span></button>)}</nav>{notice&&<div className="notice" role="status">{notice}</div>}<div hidden={tab!==3}><BrainView bundle={bundle}/></div>{tab===3?null:tab===0?<MolecularView bundle={bundle} profile={profile} onProfile={setProfileId} onImport={onImport} onSynthetic={onSynthetic} onNext={()=>go(1)}/>:tab===1?<StateView params={params} update={update} reset={reset} result={result} profile={profile} bundle={bundle} onNext={()=>go(2)}/>:<ExperimentView params={params} update={update}/>}<footer><span>Constructive simulation. Research use only. No patient prediction.</span><span>Scientific basis: João Valério Rocha and collaborators</span></footer><Provenance bundle={bundle}/></main></>;
}
