import React,{useMemo,useState} from 'react';
import {rankMaps,looRange} from '../core/model.mjs';
import {ScatterChart} from './Charts.jsx';
import {ResultBand} from './Controls.jsx';
export default function MolecularView({bundle,profile,onProfile,onImport,onSynthetic,onNext}){
 const ranking=useMemo(()=>rankMaps(profile.values,bundle.maps),[profile,bundle]);
 const [selectedId,setSelectedId]=useState(null);
 const selected=ranking.find(m=>m.id===selectedId)||ranking[0];
 const loo=useMemo(()=>looRange(profile.values,selected.values),[profile,selected]);
 return <><div className="workspace molecular-workspace"><aside className="parameter-rail"><h2>Molecular context</h2><label className="field-label" htmlFor="profile">Structural profile</label><select id="profile" value={profile.id} onChange={e=>onProfile(e.target.value)}>{bundle.profiles.map(p=><option key={p.id} value={p.id}>{p.label||p.id}</option>)}</select><label className="field-label" htmlFor="reference">Reference map</label><select id="reference" value={selected.id} onChange={e=>setSelectedId(e.target.value)}>{bundle.maps.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><p className="source-status">{bundle.kind==='synthetic'?'Synthetic demonstration':'Existing research aggregates'}</p><p className="hint">{bundle.kind==='synthetic'?'No biological values are bundled. The portable example uses 82 invented regional values and 30 invented reference maps.':'Saved group summaries and normative templates from the prior research pipeline. Not rederived from the cohort in this hackathon.'}</p><label className="file-button outline">Import aggregate JSON<input type="file" accept="application/json,.json" onChange={onImport}/></label><button className="text-button" onClick={onSynthetic}>Restore synthetic example</button><p className="hint">Local memory only. Imports are never sent to a server. Use aggregate data, not patient records.</p></aside><section className="plot-panel"><h2>Spatial association, not cell state</h2><div className="plot-subheading">{selected.name}</div><ScatterChart x={selected.values} y={profile.values} regions={bundle.regions}/><div className="stats-strip"><span>Spearman ρ <b data-testid="rho">{selected.rho?.toFixed(3)??'Undefined'}</b></span><span>Regions <b>82</b></span><span>Leave one region out <b>{loo?`${loo.min.toFixed(3)} to ${loo.max.toFixed(3)}`:'Undefined'}</b></span></div><p className="data-note">Descriptive calculation. No spatial null inference or significance claim. The region omission range is a sensitivity check, not a confidence interval.</p></section><aside className="states-rail"><h2>Reference comparison</h2><p className="hint">Ranked by absolute association. Multiple maps can share regional gradients.</p><div className="rank-list">{ranking.slice(0,6).map((m,i)=><button className={m.id===selected.id?'rank-row selected':'rank-row'} key={m.id} onClick={()=>setSelectedId(m.id)}><span>{i+1}</span><span>{m.name}</span><b>{m.rho?.toFixed(2)??'—'}</b></button>)}</div><p className="hint">Normative receptor maps are regional context. They do not measure individual transmitter levels or identify SST interneurons.</p></aside></div><ResultBand title="A molecular association is a starting point." button="Test competing states" onClick={onNext}>Hold every observed value fixed. Then ask whether different functions are still possible.</ResultBand></>;
}
